name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  build_runner: ^2.11.1
  flutter:
    sdk: flutter
  json_annotation: ^4.10.0
  json_serializable: ^6.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

resolution: workspace
