name: firebase_user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.7
  flutter: ^3.38.7

dependencies:
  cloud_firestore: ^6.1.2
  flutter:
    sdk: flutter
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

resolution: workspace
