name: inventory_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.7
  flutter: ^3.38.7

workspace:
  - packages/inventory_item_repository
  - packages/location_repository
  - packages/user_repository

dependencies:
  bloc: ^9.2.0
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flutter_test:
    sdk: flutter
  melos: ^7.4.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true

melos:
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- fvm dart run build_runner build
    upgrade:
      run: fvm flutter pub upgrade
