name: catalogue_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.1.0

resolution: workspace
dependencies:
  build_runner: ^2.11.1
  json_annotation: ^4.10.0
  json_serializable: ^6.12.0
