name: firebase_catalogue_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  catalogue_repository:
    path: ../catalogue_repository
  cloud_firestore: ^6.1.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.1.0

resolution: workspace
