name: firebase_auth_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  auth_repository:
    path: ../auth_repository
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

resolution: workspace
